#
# Copyright (C) 2021 The Android Open Source Project
#
# SPDX-License-Identifier: Apache-2.0
#

add_lunch_combo omni_m11q-eng
export ALLOW_MISSING_DEPENDENCIES=true
export FOX_VERSION="Kang"
export OF_MAINTAINER="aharv2951"
export OF_MAINTAINER_AVATAR="misc/atharv2951.png"
export OF_ALLOW_DISABLE_NAVBAR=0
export OF_HIDE_NOTCH=1
export OF_KEEP_DM_VERITY=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1
export FOX_RECOVERY_SYSTEM_PARTITION="/dev/block/mapper/system"
export FOX_RECOVERY_VENDOR_PARTITION="/dev/block/mapper/vendor"
export TW_DEFAULT_LANGUAGE="en"
export LC_ALL="C"
export OF_USE_GREEN_LED=0
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export OF_NO_MIUI_PATCH_WARNING=1
export FOX_USE_BASH_SHELL=1
export FOX_ASH_IS_BASH=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_SED_BINARY=1
export FOX_USE_XZ_UTILS=1
export OF_QUICK_BACKUP_LIST="/boot;/data;"
export OF_PATCH_AVB20=1
export FOX_DELETE_AROMAFM=1
export FOX_BUGGED_AOSP_ARB_WORKAROUND="1546300800"; # Tuesday, January 1, 2019 12:00:00 AM GMT+00:00
export FOX_ENABLE_APP_MANAGER=1
export OF_RUN_POST_FORMAT_PROCESS=1